modLoader="javafml"
loaderVersion="[47,)"
license="GNU GPLv3"
[[mods]]
modId="vmd"
version="${file.jarVersion}"
displayName="VMD"
authors="very_H"
description='''
The WRAQ 1.20.1 mod.
By very_H.
QQ:2016187250
e-mail:2016187250@qq.com
这是维瑞阿契的专用mod
欢迎加入维瑞阿契交流群: 184453807
欢迎加入维瑞阿契更新通知群: 693292427
'''
[[dependencies.vmd]]
modId = "curios"
mandatory = false
versionRange = "[1.20.1-5.2.0,)"
ordering= "NONE"
side= "BOTH"